### ISSUE TITLE
BoundMethodParameter references static, default instance of ConversionService

### ISSUE THREAD

**Issue by nebhale** [spring-projects/spring-hateoas#118] opened 2013-11-11 21:39 UTC
Currently the BoundMethodParameter class references a [static, default instance](https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/mvc/AnnotatedParametersParameterAccessor.java#L81) of `ConversionService`.  This means that should a user add `Converter`s to their `ApplicationContext` they will not be picked up and used.  This should be changed such that a `ConversionService` specified in the `ApplicationContext` will be used, otherwise the default will be.

**Comment by mhuffman-r7** [comment] 2015-06-04 18:50
+1

**Comment by bostond** [comment] 2015-12-01 23:43
+1

**Comment by hobo05** [comment] 2016-03-12 16:50
+1

**Comment by ismailbay** [comment] 2016-03-16 15:26
+1

**Comment by tufelix** [comment] 2016-04-18 08:23
+1

**Comment by francesc79** [comment] 2016-06-08 08:51
+1

**Comment by osvaldopina** [comment] 2016-06-08 23:03
I developed a [framework](https://github.com/osvaldopina/linkbuilder) to render links in spring hateoas projects. It also supports rendering links for user defined types. An explanation can be found in this [stackoverflow answer](http://stackoverflow.com/a/37714119/5144732)

**Comment by snowe2010** [comment] 2016-08-25 16:13
Is there an end in sight for this bug? It's been open for almost 2 years and none of the provided solutions have worked in our situation.

**Comment by bobonaut** [comment] 2016-10-10 13:07
+1

**Comment by aksdb** [comment] 2016-10-27 07:38
+1

**Comment by galovics** [comment] 2017-01-27 21:46
Is there any progress here?

**Comment by raulgomis** [comment] 2017-02-20 14:24
@olivergierke any progress here?

**Comment by lcaille** [comment] 2017-07-05 09:23
+1

**Comment by rgacki** [comment] 2017-08-27 21:16
+1

This hit me hard at the end of a project. This needs to be fixed!!!

**Comment by gregturn** [comment] 2017-08-28 18:32
Need to figure out a pared back version of this. The issue is against Spring Data JPA + Spring Data REST, so it's current incarnation requires hooking together lots of components. If there is a Spring HATEOAS-specific issue, need a much simpler case to illustrate.

**Comment by rgacki** [comment] 2017-08-30 10:07
A simple case:

I have controller method parameter with custom types that are annotated with annotations such as @PathVariable or @RequestParam. While Spring MVC is behaving correctly by using my custom `org.springframework.core.convert.converter.Converter`s, spring-hateoas is not using these converters when Links to the methods are built with `org.springframework.hateoas.mvc.ControllerLinkBuilder` and values are passed to the proxied method call.

A (simplified) code example:

```
@Controller
@RequestMapping("/users/{userId}")
public class UserProfileController {

    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    public ModelAndView showProfile(final @PathVariable("userId") String userId,
                                    final @RequestParam(required = false) UriTemplate customVariable) {
        final Map<String, Object> model = new HashMap<>();
        final URI action = ControllerLinkBuilder.linkTo(ControllerLinkBuilder.methodOn(UserProfileController.class).updateProfile(userId, customVariable, null))
                .toUri();
        model.put("formAction", action);
        return new ModelAndView("template", model);
    }

    @PostMapping(consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE, produces = MediaType.TEXT_HTML_VALUE)
    public ModelAndView updateProfile(final @PathVariable("userId") String userId,
                                      final @RequestParam(required = false) UriTemplate customVariable,
                                      final UserForm form) {
        ....
    }

}
```

Without my hack, creating the form action URI would result in a `ConverterNotFoundException` thrown by the ConversionService from within the `AnnotatedParametersParameterAccessor`.

I am not using Spring Data / Spring Data REST.

**Comment by gregturn** [comment] 2017-08-30 11:46
Spring HATEOAS at its core has a static conversion service setup to support the static factory methods. The related commit is a first swing at injecting an override. I wanted to discuss it with Oliver since many things are starting to come out as consequences of these static helpers.

**Comment by caoyuanqi** [comment] 2017-08-31 13:05
Just post a temporary Config Fix in Spring boot, with help from https://stackoverflow.com/questions/22240155/converter-from-pathvariable-domainobject-to-string-using-controllerlinkbuilde/22263269#22263269

```

/**
 * This configuration file is to fix bug of Spring Hateoas.
 * please check https://github.com/spring-projects/spring-hateoas/issues/118.
 */

@Component
public class MvcConfig extends WebMvcConfigurerAdapter {

    @Autowired
    private ApplicationContext applicationContext;

    @Override
    public void addFormatters(final FormatterRegistry registry) {
        super.addFormatters(registry);

        try {
            Class<?> clazz = Class.forName("org.springframework.hateoas.mvc."
                    + "AnnotatedParametersParameterAccessor$BoundMethodParameter");
            Field field = clazz.getDeclaredField("CONVERSION_SERVICE");
            field.setAccessible(true);
            DefaultFormattingConversionService service =
                    (DefaultFormattingConversionService) field.get(null);
            for (Formatter<?> formatter : applicationContext
                    .getBeansOfType(Formatter.class).values()) {
                service.addFormatter(formatter);
            }
            for (Converter<?, ?> converter : applicationContext
                    .getBeansOfType(Converter.class).values()) {
                service.addConverter(converter);
            }
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }
}
```

**Comment by gregturn** [comment] 2017-09-01 17:08
@caoyuanqi While you're doing that reflection magic, you may find Spring Framework's ReflectionUtils and ReflectionTestUtils something of interest to make interacting with Java's Reflection API a little easier to use.

**Comment by matthenry87** [comment] 2019-04-19 17:57
+1

**Comment by Zachery-Harley** [comment] 2019-07-12 13:39
+1

**Comment by hdpe** [comment] 2020-01-17 09:21
@laszlocsontos's [solution above](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-380015861) still works well for 1.0.3 with the change:

```
private static final String APPA$BMP_CLASS =
        "org.springframework.hateoas.server.core.WebHandler$HandlerMethodParameter";
```

I guess `...BMP_CLASS` could also do with renaming.

Thanks

**Comment by aisensiy** [comment] 2020-01-21 15:05
> @laszlocsontos's [solution above](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-380015861) still works well for 1.0.3 with the change:
> 
> ```
> private static final String APPA$BMP_CLASS =
>         "org.springframework.hateoas.server.core.WebHandler$HandlerMethodParameter";
> ```
> 
> I guess `...BMP_CLASS` could also do with renaming.
> 
> Thanks

It seems not working with hateoas:0.24.0. But maybe it is my mistake. I have a converter like this:

```java
@Component
public class StringToJodaTimeConverter implements Converter<String, DateTime> {

  @Override
  public DateTime convert(@NotNull String source) {
    return DateTime.parse(source, DateTimeFormat.forPattern("YYYY-MM-dd HH:mm:ss").withZoneUTC());
  }
}
```

And the method signature looks like this:

```java
public ResponseEntity getRequests(
      @RequestParam(value = "to", required = false) DateTime upTo,
      @AuthenticationPrincipal User current) {
```

I am trying to convert the `DateTime upTo` field. The hateoas used like this:

```java
linkTo(methodOn(ServingVersionRequestsApi.class).getRequests(DateTime.now(UTC), null)).withRel("next")
```

**Comment by eirikaho** [comment] 2020-04-08 05:59
Still not resolved in 1.0.4. @laszlocsontos [solution above](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-380015861) with @aisensiy [modification](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-576723290) is necessary still.

**Comment by ericjalal** [comment] 2020-10-29 18:22
Can someone please clarify what is the situation with this problem? since this [solution](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-380015861) does not even work anymore since there is no more org.springframework.hateoas.mvc.AnnotatedParametersParameterAccessor .

**Comment by eirikaho** [comment] 2020-10-30 14:27
> Can someone please clarify what is the situation with this problem? since this [solution](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-380015861) does not even work anymore since there is no more org.springframework.hateoas.mvc.AnnotatedParametersParameterAccessor .

I use the solution from @laszlocsontos with @aisensiy [modification](https://github.com/spring-projects/spring-hateoas/issues/118#issuecomment-576723290)  with spring HATEOAS 1.1.2. 

TL:DR; 
change `org.springframework.hateoas.mvc.AnnotatedParametersParameterAccessor$BoundMethodParameter` to `org.springframework.hateoas.server.core.WebHandler$HandlerMethodParameter`

**Closed** 2021-01-25 18:19 UTC
Labels: type: enhancement

**Comment by odrotbohm** [comment] 2021-01-25 18:39
This is in place now. We look up the `ConversionService` from the `ApplicationContext` associated with the current request and fall back to a default instance of none available. Feel free to give the 1.3 snapshots a try.
