### ISSUE TITLE
Problem.ExtendedProblem has no withStatus method

### ISSUE THREAD

**Issue by mkhl** [spring-projects/spring-hateoas#1313] opened 2020-06-25 10:45 UTC
```
Problem.create(payload).withStatus(CONFLICT)
```

creates a Problem instance with no payload.
I would have expected an ExtendedProblem instance (with the given payload) instead.

It seems that ExtendedProblem overrides the other `with…` methods to return an ExtendedProblem, but not `withStatus`.

**Comment by gregturn** [comment] 2020-06-26 14:06
Ahh. Yes, I see that.

The issue is that the "withers" against the base `Problem` type return `Problem`, and hence any extensibility is lost.

An immediate work-around is to swap the order, like this: `Problem.create().withStatus(HttpStatus.OK).withProperties("payload")`

This way, the `withProperties()` (which is what `.create(/*payload*/)` invokes) does that. But I agree this isn't ideal.

**Comment by gregturn** [comment] 2020-06-26 14:08
Looking deeper, it appears that `withStatus()` was never extended inside `ExtendedProblem` the way all the others are.

**Comment by gregturn** [comment] 2020-06-26 14:15
Okay, I read this issue half-focused on other stuff. Indeed, you're correct. We just one extra method on `ExtendedProblem` to close the loop.

**Comment by gregturn** [comment] 2020-06-26 16:22
Resolved via 27fe7de1.

**Comment by gregturn** [comment] 2020-06-26 16:23
Thanks @mkhl. Feel free to test out the snapshots!

**Closed by gregturn** 2020-06-26 16:22 UTC
Labels: in: mediatypes, type: bug
