### ISSUE TITLE
ControllerLinkBuilderFactory should resolve placeholders

### ISSUE THREAD

**Issue by 51f0x** [spring-projects/spring-hateoas#220] opened 2014-07-25 10:54 UTC
The ControllerLinkBuilderFactory does not resolve placeholders in RequestMapping annotations.

Ex. @RequestMapping(value = "${myPath}/users")

The handling should be the same as in the RequestMappingHandlerMapping.

Stacktrace: 

java.lang.IllegalArgumentException: Map has no value for 'myPath'
    at org.springframework.web.util.UriComponents$MapTemplateVariables.getValue(UriComponents.java:277) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:221) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents$FullPathComponent.expand(HierarchicalUriComponents.java:642) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:311) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:46) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.UriComponents.expand(UriComponents.java:152) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.web.util.UriComponentsBuilder.buildAndExpand(UriComponentsBuilder.java:288) ~[spring-web-4.0.5.RELEASE.jar:4.0.5.RELEASE]
    at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:145) ~[spring-hateoas-0.15.0.RELEASE.jar:na]
    at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:135) ~[spring-hateoas-0.15.0.RELEASE.jar:na]

**Comment by sp00m** [comment] 2015-07-25 17:29
Any fix planned for this issue? Reproducible with spring-hateoas 0.17.0.RELEASE.

**Comment by sp00m** [comment] 2015-09-21 09:57
A solution could be to make `AnnotationMappingDiscoverer.getMapping(Class<?>, Method)` call `applicationContext.getBeanFactory().resolveEmbeddedValue(...)` before returning the discovered mapping, what do you think about it?

**Comment by m7t3n** [comment] 2015-09-21 11:08
Sure, this would be a good solution.

**Comment by sp00m** [comment] 2015-09-22 12:57
I haven't been able to implement the fix in spring-hateoas directly, since `AnnotationMappingDiscoverer` isn't a Spring managed bean, and I can't find a way to access an `EmbeddedValueResolverAware` instance then... I hope someone who masters Spring better than me will be able to handle it ;)

I implemented a temporary fix in my projects through an `UriComponentsContributor` in my projects, see [`UriPlaceholdersResolver`](https://github.com/jrestful/server/blob/master/core/src/main/java/org/jrestful/web/hateoas/support/UriPlaceholdersResolver.java) and [`LinkBuilder`](https://github.com/jrestful/server/blob/master/core/src/main/java/org/jrestful/web/hateoas/support/LinkBuilder.java).

**Comment by gregturn** [comment] 2020-07-30 14:39
Resolved via #361.

**Closed by gregturn** 2020-07-30 14:39 UTC
