### ISSUE TITLE
Support Meta-Annotations When Resolving Mappings

### ISSUE THREAD

**Issue by CompileThis** [spring-projects/spring-hateoas#450] opened 2016-05-03 14:21 UTC
Spring 4.2 adds much better support for meta-annotations which are really handy to use with `@RequestMapping` to set default values for consumes/produces attributes or merge a few annotations together.

Unfortunately, this doesn't work with spring-hateoas as it uses the `findAnnotation` methods on `AnnotationUtils` rather than the new `findMergedAnnotation` methods on `AnnotatedElementUtils`.

I started writing a pull request for this capability, but it is really hard to write any tests (implementation is OK if a bit evil) for this functionality that still works in the non-Spring 4.2 Maven profile as the `@AliasFor` annotation is not available.

Is this something that anyone but me would find useful and will the next release of spring-hateoas support versions of Spring < 4.2 anyway?

**Comment by ukdave** [comment] 2016-06-17 08:27
+1 Just ran into this exact problem - I started trying to use the new @GetResource from spring-composed, but the links generated by the link builder are wrong because it no longer finds the correct mapping.

**Comment by mle-enso** [comment] 2016-11-18 18:35
+1

**Comment by olivergierke** [comment] 2016-12-07 11:25
Duplicate of the already solved #471.

**Closed by olivergierke** 2016-12-07 11:25 UTC
