### ISSUE TITLE
ControllerLinkBuilder to create templated links

### ISSUE THREAD

**Issue by matthewdfleming** [spring-projects/spring-hateoas#234] opened 2014-08-23 21:13 UTC
So my issue is that I would like to use the ControllerLinkBuilder to generate rfc6570 links. Right now it works fine with parameter substitution when I know the parameter values..

I'd love to be able to do something like this:

`Link link = linkTo(methodOn(ClientsResource.class).get(DUMMY)).withRel("clientById")`

To point to the method:

```
    @RequestMapping(value = "/clients/{id}", method = RequestMethod.GET)
    public ResponseEntity<ClientResource> get(@PathVariable("id") Long id)
```

I can obviously do that when I have a true parameter for the ID but I'd like to be able to publish a link to my application client in a templated way so that the link comes back as:

`http://localhost:8080/whatever/clients{/id}`.

This would also help me on 'search' kinds of links where the parameters are variable.

**Comment by fdw** [comment] 2015-02-16 15:06
Has there been any progress on this issue? I'd like to use templated links as well.

**Comment by xenji** [comment] 2015-10-09 15:16
Is this the same as #169 ?

**Comment by matthewdfleming** [comment] 2015-10-09 15:24
At a high level it's the same kind of problem. The difference between the two is that this issue isn't about pagination or PagedResources.. I need this kind of link building for any parameters.

**Comment by xenji** [comment] 2015-10-09 15:40
Ok, from that perspective I agree. Btw. I need it also for any kind of params. As a quick fix, I will try to "copy" the current builder and change it to behave like I want. But this is ugly and I really like to get rid of that technical dept. 

@olivergierke If you can point out some kind of implementation idea, I am willing to write the code. I am just not deep enough into the source (and sadly no spare time left to do so) to create this on my own.

**Comment by matthewdfleming** [comment] 2015-10-09 15:59
Yeah on our project, we're pretty much doing what I outlined above (and have polluted our Resource/ResourceBuilder classes).. 

I think the existing stack is useful for making links from a known entity to another.. like when I have a ParentResource making a link to a collection of ChildResource objects. The problem I have is how to get the link/rel to the collection of ParentResource objects that have no parent?

I'm not sure how hateoas solves this problem in general, but the 'hack' we're using allows us to make templated links that return objects that have no Parent context. E.g. when I have a front-end url like /parent/1 and I want to view Parent #1 without the 'context' of a search happening.

**Comment by fdw** [comment] 2016-10-25 12:02
Is there anything planned for this feature? I'd say it's one of the most basic ideas for HATEOAS, but the support could be better.

**Comment by olivergierke** [comment] 2016-12-07 11:10
Resolving as a duplicate of #169.

**Closed by olivergierke** 2016-12-07 11:10 UTC
