### ISSUE TITLE
Serializing ResourceSupport types into HAL-FORMS doesn't work.

### ISSUE THREAD

**Issue by rainer198** [spring-projects/spring-hateoas#729] opened 2018-07-19 09:18 UTC
Hello,

As it seems, rendering affordance instances of links does only work if the resource is an instance of Resource<> or Resources<>. Is it planned to also support ResourceSupport?

Further question:
- While debugging the above issue, I've seen that only affordances attached to 'self' rels are considered. (HalFormsSerializer::findTemplates) . Why this? To my understanding, you use templates to inform the client about the required payload for some LINK. Example: I have an entity resource with rel/link to edit such a resource. The @RequestBody of the POST method is modeled as different resource since not all properties of the entity should be editable, let's say EditEntityRequest. In this setting the template would not be contained in the response becazse the rel of the link is 'edit'.

Last question: when can we expect the Affordance API to be released?

**Comment by gregturn** [comment] 2018-07-19 12:08
ResourceSupport should also work. Got a test case I can examine?

As for “self” links being the only Affordances used, that’s the spec definition of HAL-FORMS. Or rather, HAL-FORMS assumes all template entries are based on the “self” URI. Which kind of makes sense since there is no uri attribute inside a template, since the templates are for “this” resource (“self” is the REST equivalent of a “this” pointer). 

If you have a different URI for editing a resource, that’s arguably a relic from pre-REST app construction. If you instead think of PUTing the current uri, that is the RESTful way to “edit” a resource by updating/replacing it. Think of a uri referencing a “thing” instead of being an action (SOAP is action based). 

As for availability it’s already released in Spring snapshots at 1.0.0.BUILD-SNAPSHOT.

**Comment by rainer198** [comment] 2018-07-19 12:30
Hi, 

the following example works (i.e. _templates are rendered)

`

@RestController
@RequestMapping(path = "/testafford", produces = MediaTypes.HAL_FORMS_JSON_VALUE)
public class TestAffordanceController {

	@GetMapping
	public Resource<AffordEntity> getTestAfford() {
		return new Resource<>(new AffordEntity(), Arrays.asList(
				linkTo(methodOn(TestAffordanceController.class).createTestAfford(null)).withSelfRel()));
	}

	@PostMapping
	public Resource<AffordEntity> createTestAfford(@RequestBody final AffordEntity body) {
		return new Resource<>(new AffordEntity(), Arrays.asList(
				linkTo(methodOn(TestAffordanceController.class).createTestAfford(null)).withSelfRel()
						.andAffordance(afford(methodOn(TestAffordanceController.class).createTestAfford(null)))));
	}

	public class AffordEntity {

		String myIdd = "1";

		String name = "Joe";

		public String getMyId() {
			return myIdd;
		}

		public void setMyId(final String id) {
			myIdd = id;
		}

		public String getName() {
			return name;
		}

		public void setName(final String name) {
			this.name = name;
		}

	}
}
`

Now, I turn the entity into a subclass of ResourceSupport instead of wrapping the result into Resource<>. The resulting payload only contains _links but no _templates

`@RestController
@RequestMapping(path = "/testafford", produces = MediaTypes.HAL_FORMS_JSON_VALUE)
public class TestAffordanceController {

	@GetMapping
	public AffordEntity getTestAfford() {
		AffordEntity result = new AffordEntity();
		result.add(linkTo(methodOn(TestAffordanceController.class).createTestAfford(null)).withSelfRel()
				.andAffordance(afford(methodOn(TestAffordanceController.class).createTestAfford(null))));
		return result;
	}

	@PostMapping
	public AffordEntity createTestAfford(@RequestBody final AffordEntity body) {
		AffordEntity result = new AffordEntity();
		result.add(linkTo(methodOn(TestAffordanceController.class).createTestAfford(null)).withSelfRel()
				.andAffordance(afford(methodOn(TestAffordanceController.class).createTestAfford(null))));
		return result;
	}

	public class AffordEntity extends ResourceSupport {

		String myIdd = "1";

		String name = "Joe";

		public String getMyId() {
			return myIdd;
		}

		public void setMyId(final String id) {
			myIdd = id;
		}

		public String getName() {
			return name;
		}

		public void setName(final String name) {
			this.name = name;
		}

	}
}`

**Comment by rainer198** [comment] 2018-07-19 12:51
Regarding your comments on my _pre-REST app construction_: I think a benefit of HATEOAS is that server can tell the client about possible application state changes. 

Let's assume a puchase order entity which has a certain state (PLACED, SHIPPED, CANCELED, ...). You could have HATEOAS links to transition the order, depending on the current state (e.g. if an order is canceled, you won't get the link for shipping). This can also be REST-full. 

Without templates, you could add a GET link to /order/123/ship and receive a template shipping request telling the client what to provide for successfully shipping an order (e.g. some address field). This shipping request would contain a POST link to /order/123/ship which finally ships the order.

If everything was just about POST/PUT/DELETE/GET of Rest resources to the self URI, why implementing HATEOAS at all?

Having read your comments, I now understand why _templates are not part of the link to which I have added the affordance. I would love that but of course, it then would not be hal-forms any more ;-)

**Comment by gregturn** [comment] 2019-01-15 20:37
If you look at https://spring.io/guides/tutorials/rest/, it includes examples showing how to add these conditional links based on the state of the underlying resource.

**Comment by gregturn** [comment] 2019-02-05 20:50
@rainer198 the tutorial listed above shows how to add transient links. And there is also https://github.com/spring-projects/spring-hateoas-examples.

**Comment by gregturn** [comment] 2019-02-15 17:05
Confirmed.

It appears the code where we sandwich HAL-FORMS between `ResourceSupport` from HAL and `Resource` support with HAL-FORMS has resulted in a gap. Need to capture this in a solid unit test and then code a solution.

**Comment by jadengis** [comment] 2019-05-14 04:22
I just experienced this issue with 1.0.0.M1. `_template` properties were rendering for extensions of `EntityModel` but not `RepresentationModel`.

**Comment by odrotbohm** [comment] 2019-06-27 15:03
PR merged, fix in place. Feel free to give the snapshots a try!

**Closed by odrotbohm** 2019-06-27 15:03 UTC
Labels: in: mediatypes, type: bug
