### ISSUE TITLE
linkTo methodOn includes port 443 with HTTPS

### ISSUE THREAD

**Issue by dlvenable** [spring-projects/spring-hateoas#327] opened 2015-03-31 20:49 UTC
When using:

linkTo(methodOn(MyController.class).getSomething(value)).toUri()

The resulting URI includes port 443.
https://myhost.com:443/my/controller

It should only be
https://myhost.com/my/controller

It is certainly not a terrible bug, but it is redundant.

**Comment by olivergierke** [comment] 2015-05-21 13:17
Is this a duplicate of #301?

**Comment by dlvenable** [comment] 2015-05-22 01:54
@olivergierke, from reading the description I believe it is.

**Closed** 2015-07-04 06:30 UTC
Labels: waiting-for-feedback
