### ISSUE TITLE
Map content is not getting serialized properly

### ISSUE THREAD

**Issue by uber-cool** [spring-projects/spring-hateoas#1352] opened 2020-08-11 17:10 UTC
spring-hateoas version: **1.2.0-SNAPSHOT**
When the content is a `Map` in `EntityModel`, it is not getting converted in proper `JSON`. The content is getting _duplicated._

Test case to describe this behavior:
```
        @Test
	public void testSerializationOfMap() throws JsonProcessingException {
		final Map map = new HashMap();
		map.put("key", "value");
		final String serialized = new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(EntityModel.of(map));

		System.out.println("Incorrect representation, key value are duplicating at root level as well as under content");
		System.out.println(serialized);

		class KeyValue {
			public KeyValue(String value) {
				key = value;
			}
			public String key;
		}

		KeyValue keyValue = new KeyValue("value");
		final String serializedKeyValue = new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(EntityModel.of(keyValue));
		System.out.println("Correct representation when using custom class KeyValue");
		System.out.println(serializedKeyValue);
	}
```

**Comment by odrotbohm** [comment] 2020-08-11 17:38
This test contains the invalid assumption that a bare `ObjectMapper` was supposed to create a valid representation which it is not. You need to register the Jackson module and `HandlerInstantiator` for the media type you want this to be rendered for.

**Comment by gregturn** [comment] 2020-08-11 17:46
Actually, I coded this test case inside `Jackson2HalIntegrationTest`...

```java
@Test
void foo() throws JsonProcessingException {

	Map<String, String> map = new TreeMap<>();
	map.put("key", "value");
	map.put("key2", "value2");

	EntityModel<Map<String, String>> entityModel = EntityModel.of(map);
	entityModel.add(Link.of("http://example.com"));

	String serialized = mapper.writeValueAsString(entityModel);

	assertThat(serialized).isEqualTo("{\"content\":{\"key\":\"value\",\"key2\":\"value2\"},\"_links\":{\"self\":{\"href\":\"http://example.com\"}},\"key\":\"value\",\"key2\":\"value2\"}");

	SomeSample sample = new SomeSample();
	sample.name = "foobar";
	EntityModel<SomeSample> entityModel2 = EntityModel.of(sample);
	entityModel2.add(Link.of("http://example.com"));

	assertThat(mapper.writeValueAsString(entityModel2)).isEqualTo("{\"name\":\"foobar\",\"_links\":{\"self\":{\"href\":\"http://example.com\"}}}");
}
```

This does confirm that wrapping a `Map` with `EntityModel` appears to duplicate data (while a POJO has no issues).

**Comment by gregturn** [comment] 2020-08-11 17:50
Looks like the problem is here, inside `EntityModel`:

```java
/**
 * Returns the underlying entity.
 *
 * @return the content
 */
@JsonUnwrapped
@Nullable
public T getContent() {
		return content;
}

// Hacks to allow deserialization into an EntityModel<Map<String, Object>>

@Nullable
@JsonAnyGetter
@SuppressWarnings("unchecked")
private Map<String, Object> getMapContent() {
	return Map.class.isInstance(content) ? (Map<String, Object>) content : null;
}
```

Only one of these two methods should ever return data.

**Comment by gregturn** [comment] 2020-08-11 17:51
This seems to do the trick:

```java
@JsonUnwrapped
@Nullable
public T getContent() {
	return Map.class.isInstance(content) ? null : content;
}
```

```java
@Test
void foo() throws JsonProcessingException {

	Map<String, String> map = new TreeMap<>();
	map.put("key", "value");
	map.put("key2", "value2");

	EntityModel<Map<String, String>> entityModel = EntityModel.of(map);
	entityModel.add(Link.of("http://example.com"));

	String serialized = mapper.writeValueAsString(entityModel);

	assertThat(serialized).isEqualTo("{\"_links\":{\"self\":{\"href\":\"http://example.com\"}},\"key\":\"value\",\"key2\":\"value2\"}");
}
```

**Comment by gregturn** [comment] 2020-08-11 17:54
Looks like we have at least one unit test that only verifies the Map property appears at the root level, but does NOT demonstrate the duplication. Working...

**Comment by uber-cool** [comment] 2020-08-11 17:59
> This test contains the invalid assumption that a bare `ObjectMapper` was supposed to create a valid representation which it is not. You need to register the Jackson module and `HandlerInstantiator` for the media type you want this to be rendered for.



> This test contains the invalid assumption that a bare `ObjectMapper` was supposed to create a valid representation which it is not. You need to register the Jackson module and `HandlerInstantiator` for the media type you want this to be rendered for.

@odrotbohm 
I am pointing that serialization works differently when content is Map and when it is a POJO. I added two cases the output should be same but it is not.

@gregturn has got the problem and the fix he suggested seems working. I think this has to be fixed in hateoas.

**Comment by odrotbohm** [comment] 2020-08-11 18:14
Yes, you're correct.`Jackson2HalIntegrationTest.rendersMapContentCorrectly()` indeed only checks for the map to be serialized, not the content being omitted.

**Comment by odrotbohm** [comment] 2020-08-12 07:36
That should be fixed. We had to go with a custom unwrapping serializer as we still need `getContent()` to return the `Map` for programatic clients. Snapshots available in a few minutes.

**Closed** 2020-08-12 07:36 UTC
Labels: in: core, process: in progress, type: bug

**Comment by uber-cool** [comment] 2020-08-12 13:10
@gregturn ,
I think this fix has broke CollectionModel serialization now
Try to serialize the object created here https://github.com/spring-projects/spring-hateoas/blob/master/src/test/java/org/springframework/hateoas/CollectionModelUnitTest.java#L38

```java
String serialized = new ObjectMapper().writerWithDefaultPrettyPrinter()
         .writeValueAsString(resource);
System.out.println(serialized);
```

Now it is throwing exception:
```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)

	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2151)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:233)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._verifyPrettyValueWrite(JsonGeneratorImpl.java:223)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._verifyValueWrite(WriterBasedJsonGenerator.java:917)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGenerator.java:400)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at org.springframework.hateoas.EntityModel$MapSuppressingUnwrappingSerializer.serialize(EntityModel.java:217)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1217)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1086)
	at org.springframework.hateoas.CollectionModelUnitTest.equalsForSelfReference(CollectionModelUnitTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by odrotbohm** [comment] 2020-08-12 13:39
We see all downstream tests (also Spring Data REST) pass. Let me reiterate on the fact that the model objects are **not intended to be serializable by an unconfigured `ObjectMapper`**. The HAL support registers a custom `CollectionModelMixin` that tweaks the serialization of `CollectionModels`.
