### ISSUE TITLE
linkTo(methodOn()) don't work properly 

### ISSUE THREAD

**Issue by alexcibotari** [spring-projects/spring-hateoas#490] opened 2016-09-16 11:38 UTC
When I use **linkTo(methodOn())** 
```
@RestController
@RequestMapping(path = "/api/issues")
public class IssueResourceController {

...

@GetMapping("{key}/worklogs")
    public ResponseEntity<Resources<WorkLogResource>> issueWorkLogs(@PathVariable String key) {
        Link link = linkTo(methodOn(this.getClass()).issueWorkLogs(key)).withSelfRel();
```
as Link I received Controller path '/api/issues' instead of '/api/issues/{key}/worklogs'

**Comment by olivergierke** [comment] 2016-09-16 12:28
Looks like a duplicate of #471.

**Closed by olivergierke** 2016-09-16 12:28 UTC
Labels: duplicate
